---
title: "MB5370_Rmarkdown_Assignment"
author: "Chik Hei Yeung"
date: "2024-05-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# installing and running packages 
```{r}
#install.packages("reader")
library(reader)
figure_dataset <- read.csv("figure_dataset.csv")
View (figure_dataset)
```
```{r}
#install.packages("tidyverse")
library(tidyverse)
```
# Paper of original figure 
### The paper used a figure comparing catch rates of blue fin tuna with percent over catch. The figure used two y axis which can make the data missleading and it made the figure hard to read. 
### https://www.sciencedirect.com/science/article/pii/S0308597X1200036X#bib18 
### We re plotted the figure and instead separated the two graphs so they can be compared seperatly. 

# Graphing the data 
```{r}
ggplot(data = figure_dataset) + 
  geom_line(mapping = aes(x = year, y = reported_catch)) +
  labs(title = "Reported catch of blue fin tuna", x = "Year", y = "Tonnes")
```

```{r}
ggplot(data = figure_dataset) + 
  geom_line(mapping = aes(x = year, y = percent_overcatch)) +
  labs(title = "Percent estimate of overcatch", x = "Year", y = "Percent overcatch")
```








